/*
--ELIMINAR TABLAS EN ORDEN
DROP TABLE VENTA_DETALLE ;
DROP TABLE VENTA;
DROP TABLE PRODUCTO;
DROP TABLE CATEGORIA;
DROP TABLE PERSONA;
*/

--CREAR LAS TABLAS
CREATE TABLE PERSONA (
    IDPER int  NOT NULL,
    DNIPER char(8)  NOT NULL,
    NOMPER varchar2(50)  NOT NULL,
    APEPER varchar2(50)  NOT NULL,
    EMAPER varchar2(80)  NOT NULL,
    CELPER char(9)  NOT NULL,
    TIPPER char(1)  NOT NULL,
    ESTPER char(1) DEFAULT 'A' NOT NULL,
    FECNACPER DATE NOT NULL,
    CONSTRAINT PERSONA_pk PRIMARY KEY (IDPER)
) ;
CREATE TABLE CATEGORIA(
    IDCAT INT NOT NULL,
    NOMCAT varchar2(50)  NOT NULL,
    CONSTRAINT CATEGORIA_pk PRIMARY KEY (IDCAT)
);

CREATE TABLE PRODUCTO(
    CODPROD varchar2(50)  NOT NULL,
    NOMPRO varchar2(50)  NOT NULL,
    IDCATPRO int NOT NULL,
    PREPRO decimal(8,2)  NOT NULL,
    STOCKPRO int NOT NULL,
    ESTPRO char(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT PRODUCTO_pk PRIMARY KEY (CODPROD)
);

CREATE TABLE VENTA(
    IDVEN INT NOT NULL,
    FECVEN date NOT NULL,
    IDVEND int NOT NULL,
    IDCLI int NOT NULL,
    TIPPAGVEN char(1)  NOT NULL,
    ESTVEN char(1) DEFAULT 'A' NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY (IDVEN)
);

--CREAR LA TABLA  VENTA_DETALLE
CREATE TABLE VENTA_DETALLE(
    IDVENDET INT NOT NULL,
    IDVEN int NOT NULL,
    CODPRO varchar2(50)  NOT NULL,
    CANVENDET NUMBER NOT NULL,
    CONSTRAINT VENTA_DETALLE_pk PRIMARY KEY (IDVENDET)
);
--RELACIONES DE LA TABLAS
ALTER TABLE PRODUCTO ADD CONSTRAINT PRODUCTO_CATEGORIA
    FOREIGN KEY (IDCATPRO)
    REFERENCES CATEGORIA (IDCAT);
    
ALTER TABLE VENTA ADD CONSTRAINT VENTA_VENDEDOR
    FOREIGN KEY (IDVEND)
    REFERENCES PERSONA (IDPER);

ALTER TABLE VENTA ADD CONSTRAINT VENTA_CLIENTE
    FOREIGN KEY (IDCLI)
    REFERENCES PERSONA (IDPER);
    
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_VENTA
    FOREIGN KEY (IDVEN)
    REFERENCES VENTA (IDVEN);
    
ALTER TABLE VENTA_DETALLE ADD CONSTRAINT VENTA_DETALLE_PRODUCTO
    FOREIGN KEY (CODPRO)
    REFERENCES PRODUCTO (CODPROD);
    
---SECUENCIAS
CREATE SEQUENCE INC_PER
START WITH 200
INCREMENT BY 1;

CREATE SEQUENCE INC_CAT
START WITH 10
INCREMENT BY 10;

CREATE SEQUENCE INC_VEN
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE INC_VEN_DET
START WITH 300
INCREMENT BY 1;
---TRIGGERS

CREATE TRIGGER TRG_INC_PER
  BEFORE INSERT ON PERSONA
  FOR EACH ROW
  BEGIN
    SELECT INC_PER.NEXTVAL INTO :NEW.IDPER FROM DUAL;
  END;
  /
  
  CREATE TRIGGER TRG_INC_CAT
  BEFORE INSERT ON CATEGORIA
  FOR EACH ROW
  BEGIN
    SELECT INC_CAT.NEXTVAL INTO :NEW.IDCAT FROM DUAL;
  END;
  /
  
  CREATE TRIGGER TRG_INC_VEN
  BEFORE INSERT ON VENTA
  FOR EACH ROW
  BEGIN
    SELECT INC_VEN.NEXTVAL INTO :NEW.IDVEN FROM DUAL;
  END;
  /
  
  CREATE TRIGGER TRG_INC_VENDET
  BEFORE INSERT ON VENTA_DETALLE
  FOR EACH ROW
  BEGIN
    SELECT INC_VEN_DET.NEXTVAL INTO :NEW.IDVENDET FROM DUAL;
  END;
  /
  
create or replace trigger INSERTAR_FECHA  
 BEFORE insert on VENTA 
 for each row  
 begin
   :NEW.FECVEN := to_char(sysdate, 'DD/MM/YYYY HH24:MI:SS'); 
end;
/

