/* Crear tablespace TBSGAMARK */
CREATE TABLESPACE TBSGAMARK
DATAFILE 'tbsgamark.dbf'
SIZE 300M;

/* Permitor ejecución de script */
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

/* Crear usuario */
CREATE USER gmarket
IDENTIFIED BY ORCL1234  
DEFAULT TABLESPACE TBSGAMARK
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TBSGAMARK;

/* Determinar los privilegios del usuario */
GRANT CREATE SESSION TO gmarket;
GRANT CREATE TABLE TO gmarket;
GRANT CREATE VIEW TO gmarket;
GRANT CREATE PROCEDURE TO gmarket;
GRANT CREATE TRIGGER TO gmarket;
GRANT CREATE SEQUENCE TO gmarket;
GRANT CREATE JOB TO gmarket;
GRANT UNLIMITED TABLESPACE TO gmarket;